### ISSUE TITLE
siapabsensiwithsql return []

### ISSUE THREAD

**Issue by awangga** [InformaticsResearchCenter/ITeung#10]
![image](https://user-images.githubusercontent.com/11188109/78196721-7a67ab00-74ad-11ea-9fc3-f9694de60594.png)
keluarnya adalah list kosong. whyyyy????

**Comment by awangga** [comment]
harusnya kan string

**Comment by awangga** [comment]
![image](https://user-images.githubusercontent.com/11188109/78197648-27432780-74b0-11ea-89a0-7f269503a1d9.png)

**Comment by awangga** [comment]
kenapa yang attend kososng

**Comment by awangga** [comment]
![image](https://user-images.githubusercontent.com/11188109/78198264-417e0500-74b2-11ea-825c-fb2a25088445.png)

**Comment by awangga** [comment]
![image](https://user-images.githubusercontent.com/11188109/78200016-85bfd400-74b7-11ea-9ebc-bdb0baf7415d.png)

**Comment by awangga** [comment]
studentsattendace() <- penyebab error
return var[0] tidak ada mahasiswayang hadir

**Comment by dindamajesty13** [comment]
```python
def getTingkat(data):
    studentnumber = data
    median = len(studentnumber) // 2
    print('median: ' + str(median))
    if median != 0:
        studentnum = studentnumber[median - 1]
        print('studentnum: ' + str(studentnum))
        npm = getNpmandNameMahasiswa(studentnum)[0]
        print('npm: ' + str(npm))
        thn2 = npm[1:3]
        selisih = int(config.siap_tahun_id[2:4]) - int(thn2)
        tingkat = str(selisih + 1)
    else:
        tingkat = ''
    return tingkat
```

return NoneType
