### ISSUE TITLE
Help Sesuai Dengan Usernya

### ISSUE THREAD

**Issue by awangga** [InformaticsResearchCenter/ITeung#33]
keep minimalis. ketika ketik iteung help maka keluar info berdasarkan jenis usernya.

jika terlalu banyak maka iteung akan memberi tahu help selanjutnya, misal jika dosen yang request :
iteung help

mengembalikan : 
keting iteung help kuliah untuk panduan perkuliahan
ketik iteung help ujian untuk panduan UTS/UAS
ketik iteung help nilai untuk panduan input nilai
ketik iteung help siap untuk panduan reset password dan akses siap

**Comment by trianggadios** [comment]
![panduan1](https://user-images.githubusercontent.com/50858612/81371380-e8913480-9121-11ea-9701-a88ea4822c9c.PNG)
![panduan2](https://user-images.githubusercontent.com/50858612/81371382-ea5af800-9121-11ea-8e20-8016a52ee322.PNG)
![panduan3](https://user-images.githubusercontent.com/50858612/81371384-eaf38e80-9121-11ea-9fe8-6e16b57bd92e.PNG)
pengubahan di tabel iteung dan tidak menggunakan module
